BlogProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views
urlpatterns = [
    path('', include('blog.urls')),
    path('admin/', admin.site.urls),
    path('accounts/login/', views.login, name='login'),
    path('accounts/logout/', views.logout, name='logout', kwargs={'next_page':'/'}),
]

blog/urls.py
from blog import views
from django.conf.urls import url

app_name='blog'

urlpatterns=[
    url(r'^$', views.PostListView.as_view(), name='post_list'),
    url(r'^about/$',views.AboutView.as_view(), name='about'),
    url(r'^post/(?P<pk>\d+)/$', views.PostDetailView.as_view(), name='post_detail'),
    url(r'^post/new/$', views.CreatePostView.as_view(), name='post_new'),
    url(r'^post/(?P<pk>\d+)/update/$', views.PostUpdateView.as_view(), name='post_update'),
    url(r'^post/(?P<pk>\d+)/remove/$', views.PostDeleteView.as_view(), name='post_remove'),
    url(r'^post/drafts/$', views.DraftListView.as_view(), name='post_draft_list'),
    url(r'^post/(?P<pk>\d+)/comment/$', views.add_comment_to_post, name='add_comment'),
    url(r'^comment/(?P<pk>\d+)/approve/$', views.comment_approve, name='comment_approve'),
    url(r'^comment/(?P<pk>\d+)/remove/$', views.comment_remove, name='comment_remove'),
    url(r'^post/(?P<pk>\d+)/publish/$', views.post_publish, name='post_publish'),

]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    author=models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title=models.CharField(max_length=200)
    text=models.TextField()
    create_date=models.DateField(default=timezone.now)
    published_date=models.DateField(blank=True,null=True)

    def publish(self):
        self.published_date=timezone.now()
        self.save()

    def approve_comments(self):
        return self.comments.filter(approved_comment=True)

    def get_absolute_url(self):
        return reverse("blog:post_detail", kwargs={'pk':self.pk})

    def __str__(self):
        return self.title


class Comment(models.Model):
    post=models.ForeignKey('blog.Post', related_name='comments', on_delete=models.CASCADE)
    author=models.CharField(max_length=200)
    text=models.TextField()
    create_date=models.DateField(default=timezone.now)
    approved_comment= models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list')

    def __str__(self):
        return self.text

blog/forms.py
from django import forms
from blog.models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields=('author', 'title', 'text')
        widgets={
            'title':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea postcontent'})
        }

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields=('author','text')

        widgets={
            'author':forms.TextInput(attrs={'class':'textinputclass'}),
            'text':forms.Textarea(attrs={'class':'editable medium-editor-textarea'})
        }

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from django.views.generic import TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from blog.forms import PostForm,CommentForm
from django.urls import reverse_lazy
from django.utils import timezone
from django.http import HttpResponse
# Create your views here.


class AboutView(TemplateView):
    template_name='about.html'

class PostListView(ListView):
    model=Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')

class PostDetailView(DetailView):
    model=Post
    template_name='post_detail.html'


class CreatePostView(LoginRequiredMixin,CreateView):
    login_url = '/accounts/login/'
    redirect_field_name = 'blog/post_detail.html'

    form_class = PostForm

    model = Post

class PostUpdateView(LoginRequiredMixin, UpdateView):
    login_url = '/accounts/login/'
    redirect_field_name= 'blog/post_detail.html'
    form_class= PostForm
    model=Post

class PostDeleteView(LoginRequiredMixin, DeleteView):
    login_url = '/accounts/login/'
    redirect_field_name= 'blog/post_detail.html'
    model=Post
    success_url = reverse_lazy('blog:post_list')

class DraftListView(LoginRequiredMixin, ListView):
    login_url = '/accounts/login/'
    redirect_field_name= 'blog/post_list.html'
    template_name='post_draft_list.html'
    model=Post
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('create_date')

############################################################

@login_required
def post_publish(request, pk):
    post=get_object_or_404(Post, pk=pk)
    post.publish()
    return redirect('blog:post_detail',pk=pk)


@login_required
def add_comment_to_post(request, pk):
    post=get_object_or_404(Post,pk=pk)
    if request.method=='POST':
        form=CommentForm(request.POST)
        if form.is_valid():
            comment=form.save(commit=False)
            comment.post=post
            comment.save()
            return redirect('blog:post_detail',pk=post.pk)
        else:
            return HttpResponse('<h1>Comment is not valid</h1>')
    else:
        form=CommentForm()
    return render(request, 'comment_form.html', {'form':form})

@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    comment.approve()
    return redirect('blog:post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment=get_object_or_404(Comment,pk=pk)
    post_pk=comment.post.pk
    comment.delete()
    return redirect('blog:post_detail',pk=post_pk)

blog/templates/blog/about.html
{% extends 'blog/base.html' %} {% block content %}
<h1>About this company</h1>
<h2>shjt</h2>
<p>Thank you for checking it out</p>
{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    <head>
        <title>Blog Project</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

        <!-- {# MEDIUM STYLE EDITOR#}
        <script src="//cdn.jsdelivr.net/medium-editor/latest/js/medium-editor.min.js"></script>
        <link rel="stylesheet" href="//cdn.jsdelivr.net/medium-editor/latest/css/medium-editor.min.css" type="text/css" media="screen" charset="utf-8">
 -->

        {# Custom CSS#}
        <!-- <link rel="stylesheet" href="{% static 'css/blog.css' %}"> -->

        {# Fonts#}
        <link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">




  <body class='loader'>


    <nav class="navbar navbar-default techfont custom-navbar">
      <div class="container">


        <ul class="nav navbar-nav">
          <li><a class='navbar-brand bigbrand' href="{% url 'blog:post_list' %}">Blog Practice</a></li>
          <li><a href="{% url 'blog:about'%}">About</a></li>
          <li><a href="https://www.github.com">Github</a></li>
          <li><a href="https://www.linkedin.com">LinkedIn</a></li>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li>
            <a href="{% url 'blog:post_new' %}" >New Post</a>
          </li>

          <li>
            <a href="{% url 'blog:post_draft_list' %}">Drafts</a>
          </li>
          <li>
            <a href="{% url 'logout' %}" >Log out</a>
          </li>

          <li>
            <a >Welcome: {{ user.username }}</a>
          </li>
            {% else %}
            <li><a class='nav navbar-right' href="{% url 'login' %}" ><span class="glyphicon glyphicon-user"></span></a></li>
          {% endif %}

        </ul>
    </div>
  </nav>

    {# The actual blog posts#}
          <div class="content container">
              <div class="row">
                  <div class="col-md-8">
                    <div class="blog_posts">
                      {% block content %}
                      {% endblock %}

                    </div>

                  </div>
              </div>
          </div>

  {# SCRIPTS#}

  <script type="text/javascript" src="{% static 'js/blog.js' %}"></script>

  </body>
  </html>

blog/templates/blog/comment_form.html
{% extends 'blog/base.html' %} {% block content %}
<h1>New comment</h1>
<h2>ádasd</h2>
<form class='post-form' method="post">
  {% csrf_token %} {{form.as_p}}
  <button type="submit" class="save btn btn-default">Post Comment</button>
</form>
<script type="text/javascript">
  var editor = new MediumEditor('.editable')
</script> {% endblock %}

blog/templates/blog/post_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
  <form method="post">
    {% csrf_token %}
    <p>Are you sure want to delete {{object}}</p>
    <input type="submit" class='btn btn-danger' value="Delete">
  </form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1 class="posttitle loader">{{post.title}}</h1>
  <p class='postcontent'>{{post.text|safe|linebreaksbr }}</p>
    <div class="date postdate">
      {% if post.published_date %}
        <p>Publised on: {{post.published_date}}</p>
    </div>
      {% else %}
        <a class='btn btn-primary' href="{% url 'blog:post_publish' pk=post.pk %}">Publish</a>
      {% endif %}

    {% if user.is_authenticated %}
      <a href="{% url 'blog:post_update' pk=post.pk%}"><span class='glyphicon glyphicon-pencil'></a>
      <a href="{% url 'blog:post_remove' pk=post.pk%}"><span class='glyphicon glyphicon-remove'></a>
    {% endif %}

    <hr>
    <a class='btn btn-primary btn-comment' href="{% url 'blog:add_comment' pk=post.pk %}">Add comment</a>
    <div class='container'>
      {% for comment in post.comments.all %}
        <br>
          {% if user.is_authenticated or comment.approved_comment %}
            {{ comment.create_date }}

              {% if not comment.approved_comment %}
                <a class='btn btn-primary' href="{% url 'blog:comment_approve' pk=comment.pk %}"><span class='glyphicon glyphicon-ok'></span></a>
                <a class='btn btn-default' href="{% url 'blog:comment_remove' pk=comment.pk %}"><span class='glyphicon glyphicon-remove'></span></a>
              {% endif %}

            <p>{{ comment|safe|linebreaks }}</p>
            <p>Posted by: {{comment.author}}</p>
          {% endif%}
          <hr>
          {% empty %}
          <p>No Comments</p>
      {% endfor %}
    </div>
{% endblock %}

blog/templates/blog/post_draft_list.html
{% extends 'blog/base.html' %}
{% block content %}
  {% for post in post_list %}
  <div class='post'>
    <p class='date'>Created: {{post.create_date|date:'d-m-Y'}}</p>
    <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>
    <p>{{post.text|truncatechars:200}}</p>
  </div>
  {% endfor %}
{% endblock %}

blog/templates/blog/post_form.html
{% extends 'blog/base.html' %}
{% block content %}
  <h1>New Post</h1>
  <form class="post-form" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class='save btn btn-default'>Save</button>
  </form>

  <script type="text/javascript">
    var editor = new MediumEditor('.editable');
  </script>
{% endblock %}

blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
  <div class='centerstage'>
    {% for post in post_list %}
    <div class="post">
      <h1><a href="{% url 'blog:post_detail' pk=post.pk %}">{{post.title}}</a></h1>

      <div class='date'>
        <p>Publish on: {{post.published_date|date:'D M Y'}}</p>
      </div>
      <a href="{% url 'blog:post_detail' pk=post.pk %}">Comments ({{post.approve_comments.count}})</a>
    </div>
    {% endfor %}
  </div>
{% endblock %}